version: "3.5"
services:
  part_1_mongo:
    image: "mongo:latest"
    command: mongod
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
  part_2_mongo:
    image: "mongo:latest"
    command: mongod
    ports:
      - "28017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
  part_5_mongo:
    image: "mongo:latest"
    command: mongod
    ports:
      - "29017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
